#' @title Checklist of vascular plants species of the British Isles with associated data
#' @description A complete list of vascular plants currently extant on the British Isles, with associated information on taxonomy, ecology and status
#' @format A data frame with 3227 rows and 73 variables:
#' \describe{
#'   \item{\code{kew_id}}{character the Kew identification number associated with the main taxon name used in this dataset}
#'   \item{\code{unclear_species_marker}}{character Marked with "y" are species that have a high likelihood of misidentification in the field due to apomixis or other factors, members of sections, aggregates etc.}
#'   \item{\code{extinct_species_marker}}{character Marked with "E" are species that were labelled as extinct in Stace, 2019 and show no signs of re-appearance in the study area. No additional data is given for these species beyond their taxonomy.}
#'   \item{\code{taxon_name}}{character Species binomen and authority according to Stace, 2019}
#'   \item{\code{taxon_name_binom}}{character Species binomen according to Stace, 2019}
#'   \item{\code{authors}}{character Authority associated with the species binomen according to Stace, 2019}
#'   \item{\code{taxon_name_WCVP}}{character Species binomial according to World Checklist of Vascular Plants, 2020, differs from taxon_name in case of spelling differences}
#'   \item{\code{authors_WCVP}}{character Authority associated with the species binomial according to WCVP, 2020, differs from taxon_name in case of spelling differences}
#'   \item{\code{order}}{character Taxonomic rank, sensu Stace 2019: Order}
#'   \item{\code{family}}{character Taxonomic rank, sensu Stace 2019: Family}
#'   \item{\code{genus}}{character Taxonomic rank, sensu Stace 2019: Genus}
#'   \item{\code{subgenus}}{character Taxonomic rank, sensu Stace 2019: Subgenus}
#'   \item{\code{section}}{character Taxonomic rank, sensu Stace 2019: Section}
#'   \item{\code{subsection}}{character Taxonomic rank, sensu Stace 2019: Subsection}
#'   \item{\code{series}}{character Taxonomic rank, sensu Stace 2019: Series}
#'   \item{\code{species}}{character Taxonomic rank, sensu Stace 2019: Species}
#'   \item{\code{group}}{character Taxonomic rank, sensu Stace 2019: Group}
#'   \item{\code{aggregate}}{character Identity of the species binomial as eponym of an aggregate (agg), or as a member of an aggregate (in agg), “agg.”, “in agg.”, NA}
#'   \item{\code{members_of_agg.}}{character Other species associated with the aggregate eponym}
#'   \item{\code{taxonomic_status}}{factor Taxonomic status as listed in the World Checklist of Vascular plants - one of "Accepted", "Synonym", "Homotypic_Synonym", "Unplaced"}
#'   \item{\code{accepted_kew_id}}{character The Kew identification number associated with the accepted WCVP taxon name if this differs from the main taxon name}
#'   \item{\code{accepted_name}}{character The WCVP accepted taxon name if this differs from the main taxon name}
#'   \item{\code{accepted_authors}}{character The author associated with the accepted WCVP taxon name if this differs from the main taxon name}
#'   \item{\code{imperfect_match_with_Stace_IV}}{character Marked with "y" are species where name according to Stace 2019 does not match WCVP name (i.e. due to small spelling differences)}
#'   \item{\code{WCVP.URL}}{character Hyperlink to World Checklist of Vascular Plants species accession}
#'   \item{\code{POWO.URL}}{character Hyperlink to Plants of the World Online species accession}
#'   \item{\code{IPNI.URL}}{character Hyperlink to International Plant Name Index species accession}
#'   \item{\code{accepted.WCVP.URL}}{character Hyperlink to WCVP accession of accepted species name by WCVP standards, only provided if main species name is not "Accepted"} 
#'   \item{\code{StaceIV_nativity}}{factor Description of native status according to Stace 2019. "?N" = possibly native, "Arch-colonist" = Archaeophyte colonist, "Arch-cultd" = Archaeophyte cultivated, "Arch-denizen" = Archaeophyte denizen, "N" = Native, "Neo-casual" = Neophyte casual, "Neo-natd" = Neophyte naturalized, "Neo-surv" = Neophyte survivor, "Neonative"}
#'   \item{\code{Atlas_nativity.viaALIENATT_PLANTATT.}}{factor Description of native status according to Atlas of the British Isles, obtained from PLANTATT, 2008 and ALIENATT, "AC" = Alien casual, "AN" = Neophyte, "AR" = Archaeophyte, "N" = Native, "NE" = Native endemic, "NA (unclear)" = native status doubtful, or intermediate states AR/N, AR/AN, AC (or AN?), AC change to AN?, AN (or AC?), AN change to AC?, AN or AC?, AN?}
#'   \item{\code{Stace_Crawley_nativity.aliens.}}{factor Description of native status according to Alien Plants by Stace & Crawley, 2015., "Arch" = Archaeophyte, "Arch-colonist" = Archaeophyte colonist, "Arch-cultd" = Archaeophyte cultivated, "Arch-denizen" = Archaeophyte denizen, "Neo" = Neophyte, "Neo-casual" = Neophyte casual, "Neo-natd" = Neophyate naturalized, "Neo-surv" = Neophyte survivor}
#'   \item{\code{SLA}}{numeric Specific Leaf Area (total leaf area per total leaf dry mass) in mm/mg-1, mean value taken from publicly available data from TRY database, Mean: 24.46; Median: 22.45; Min: 0.51; Max: 207.78}
#'   \item{\code{LDMC}}{numeric Leaf Dry Matter Content (oven-dry mass per fresh mass) in g/g-1, mean value taken from publicly available data from TRY database, Mean: 0.22; Median: 0.21; Min: 0.04; Max: 0.68}
#'   \item{\code{seed_mass}}{numeric Seed mass in mg, mean value taken from publicly available data from TRY database, Mean: 59.09; Median: 1.24; Min: 0.0009; Max: 23993.88} 
#'   \item{\code{leaf_area}}{numeric Leaf area in mm2, mean value taken from publicly available data from TRY database, Mean: 4009.61; Median: 922.42; Min: 0.19; Max: 180611.54}
#'   \item{\code{mean_veg_height}}{numeric Vegetative plant height in m, mean value taken from publicly available data from TRY database, Mean: 2.10; Median: 0.43; Min: 0.001; Max: 76.30}
#'   \item{\code{max_veg_height}}{numeric Vegetative plant height in m, maximum value taken from publicly available data from TRY database, Mean: 3.85; Median: 0.8; Min: 0.001; Max: 120}
#'   \item{\code{L_PLANTATT}}{character Ellenberg indicator values, describing realised niche for light, small numbers indicate affinity to low light (deep shade), high numbers bright conditions, determined for British plants. Ordinal; Range: 1 - 9, 1 = low light/deep shade, 9 0= full light}
#'   \item{\code{F_PLANTATT}}{character Ellenberg indicator values, describing realised niche for moisture (German ‘Feuchtigkeit’), small numbers indicate affinity to arid conditions, values of 10 or higher describe plants living as aquatics or submerged (12), determined for British plants. Ordinal; Range: 1 - 12; 1 = highly arid soils, 9 = wet soils, 10 = aquatic plant, 12 = submerged plant}
#'   \item{\code{R_PLANTATT}}{character Ellenberg indicator values, describing realised niche for soil acidity (reactivity - R), determined for British plants. Ordinal; Range: 1 - 9; 1= highly acidic soil, 9 = alkaline soil}
#'   \item{\code{N_PLANTATT}}{character Ellenberg indicator values, describing realised niche for soil fertility (termed ’N’, due to focus on nitrogen), determined for British plants. Ordinal; Range: 1 - 9; 1 = very low nitrogen and overall nutrient availability, 9 = excessive nutrient availability}
#'   \item{\code{S_PLANTATT}}{character Ellenberg indicator values, describing realised niche for salinity, determined for British plants. Ordinal; Range: 0 - 9; 0 = no salt tolerated, 9 = extreme salinity}
#'   \item{\code{L_Doring}}{character Ellenberg indicator values, describing realised niche for light, determined for central European plants. Ordinal; Range: 1 - 9, 1 = low light/deep shade, 9 0= full light}
#'   \item{\code{F_Doring}}{character Ellenberg indicator values, describing realised niche for moisture (German ‘Feuchtigkeit’), determined for central European plants. Ordinal; Range: 1 - 12; 1 = highly arid soils, 9 = wet soils, 10 = aquatic plant, 12 = submerged plant}
#'   \item{\code{R_Doring}}{character Ellenberg indicator values, describing realised niche for soil acidity (reactivity - R), determined for central European plants. Ordinal; Range: 1 - 9; 1= highly acidic soil, 9 = alkaline soil}
#'   \item{\code{N_Doring}}{character Ellenberg indicator values, describing realised niche for soil fertility (termed ’N’, due to focus on nitrogen), determined for central European plants. Ordinal; Range: 1 - 9; 1 = very low nitrogen and overall nutrient availability, 9 = excessive nutrient availability}
#'   \item{\code{S_Doring}}{character Ellenberg indicator values, describing realised niche for salinity, determined for central European plants. Ordinal; Range: 0 - 9; 0 = no salt tolerated, 9 = extreme salinity}
#'   \item{\code{T_Doring}}{character Ellenberg indicator values, describing realised niche for temperature, determined for central European plants. Ordinal; Range: 1 - 9; 1 = extreme cold, 9 = strong heat}
#'   \item{\code{ECPE_CSR}}{character Life strategy of species as described by Grime (1974). Each species falls in to a triangular space formed by the extremities (C, S, R), describing its typical life strategy tendency. “C” = competitor, “S” = stress tolerator, “R” = ruderal; any combination for intermediate strategies (e.g. “CS”, “C/CSR”)}
#'   \item{\code{predicted_CSR}}{character Life strategy of species as described by Grime (1974). Each species falls in to a triangular space formed by the extremities (C, S, R), describing its typical life strategy tendency. “C” = competitor, “S” = stress tolerator, “R” = ruderal; any combination for intermediate strategies (e.g. “CS”, “C/CSR”)}
#'   \item{\code{growth_form}}{character Plant growth form as determined by TRY contributors Engemann and Günther. “Aquatic”, “Fern”, “Graminoid”, “Herb”, “Shrub”, “Tree”, NA}
#'   \item{\code{succulence}}{character Species that were labelled as “succulent” or exhibiting “succulence” in a query of the TRY database’s publically available data on growth form were assigned the label “succulent” in our database. “succulent”, NA}
#'   \item{\code{life_form}}{character Raunkiaer life-form; most likely category listed first; alternative life-forms afterwards. "chamaephyte", "epiphyte", "geophyte", "helophyte", "hemicryptophyte", "hydrophyte", "phanerophyte", "therophyte", or allocated to more than one of these, addition of "tree" (phanerophyte that can grow into a tree, i.e. single stemmed and tall), "vine" (both for woody and herbaceous climbers), "parasite" (for achlorophyllous species, plus Viscum)}
#'   \item{\code{biome}}{character Broad biome the species is associated with. "Arctic montane", "Boreal Montane", "Boreo-Arctic Montane", "Boreo-Temperate", "Mediterranean", "Mediterranean-Atlantic", "Southern Temperate", "Temperate", "Wide Boreal", "Wide Temperate"}
#'   \item{\code{origin}}{character Description of origin country/region (most likely candidate for area plants where introduced from; not complete foreign distribution) as mentioned in Stace 2019, only for non-natives.}
#'   \item{\code{TDWG_level_1_code}}{character TDWG level one code (Brummitt, 2001), manually determined from origin descriptions. 1: Europe, 2: Africa, 3: Asia-Temperate, 4: Asia-Tropical, 5: Australasia, 6: Pacific, 7: Northern America, 8: Southern America}
#'   \item{\code{GB_Man_hectads_post2000}}{integer Number of hectads with records of this species since 2000, from BSBI Ddb September 2020. Hectads of Great Britain (excluding Northern Ireland) and Isle of Man.}
#'   \item{\code{Ire_hectads_post2000}}{integer Number of hectads with records of this species since 2000, from BSBI Ddb September 2020. Hectads of Ireland (including Northern Ireland).}
#'   \item{\code{CI_hectads_post2000}}{integer Number of hectads with records of this species since 2000, from BSBI Ddb September 2020. Hectads of the Channel Islands.}
#'   \item{\code{GB_Man_hectads_1987_1999}}{integer Number of hectads with records of this species between 1987 and 1999, from BSBI Ddb September 2020. Hectads of Great Britain (excluding Northern Ireland) and Isle of Man.}
#'   \item{\code{Ire_hectads_1987_1999}}{integer Number of hectads with records of this species between 1987 and 1999, from BSBI Ddb September 2020. Hectads of Ireland (including Northern Ireland).}
#'   \item{\code{CI_hectads_1987_1999}}{integer Number of hectads with records of this species between 1987 and 1999, from BSBI Ddb September 2020. Hectads of the Channel Islands.}
#'   \item{\code{GB_Man_hectads_2000_2009}}{integer Number of hectads with records of this species between 2000 and 2009, from BSBI Ddb September 2020. Hectads of Great Britain (excluding Northern Ireland) and Isle of Man.}
#'   \item{\code{Ire_hectads_2000_2009}}{integer Number of hectads with records of this species between 2000 and 2009, from BSBI Ddb September 2020. Hectads of Ireland (including Northern Ireland).}
#'   \item{\code{CI_hectads_2000_2009}}{integer Number of hectads with records of this species between 2000 and 2009, from BSBI Ddb September 2020. Hectads of the Channel Islands.}
#'   \item{\code{GB_Man_hectads_2010_2019}}{integer Number of hectads with records of this species between 2010 and 2019, from BSBI Ddb September 2020. Hectads of Great Britain (excluding Northern Ireland) and Isle of Man.}
#'   \item{\code{Ire_hectads_2010_2019}}{integer Number of hectads with records of this species between 2010 and 2019, from BSBI Ddb September 2020. Hectads of Ireland (including Northern Ireland).}
#'   \item{\code{CI_hectads_2010_2019}}{integer Number of hectads with records of this species between 2010 and 2019, from BSBI Ddb September 2020. Hectads of the Channel Islands.}
#'   \item{\code{BOLD_link1}}{character Hyperlink to BOLD database, which contains barcode sequences (rbcL, matK and ITS2), herbarium specimen and details about sample collection; each hyperlink accesses a different specimen, where possible, three individual BOLD_accessions are used per species}
#'   \item{\code{BOLD_link2}}{character Hyperlink to BOLD database, which contains barcode sequences (rbcL, matK and ITS2), herbarium specimen and details about sample collection; each hyperlink accesses a different specimen, where possible, three individual BOLD_accessions are used per species}
#'   \item{\code{BOLD_link3}}{character Hyperlink to BOLD database, which contains barcode sequences (rbcL, matK and ITS2), herbarium specimen and details about sample collection; each hyperlink accesses a different specimen, where possible, three individual BOLD_accessions are used per species}
#'   \item{\code{GS_1C_pg}}{double Haploid genome size in picograms. Smallest measurement.}
#'   \item{\code{GS_2C_pg}}{double Diploid genome size in picograms. Smallest measurement.}
#'   \item{\code{GS_1C_Mbp}}{double Haploid genome size in mega base pairs. Smallest measurement.}
#'   \item{\code{GS_2C_Mbp}}{double Diploid genome size in mega base pairs. Smallest measurement.}
#'   \item{\code{from_BI_material}}{character Binary information on provenance of material used for the genome size measurement. “y” = from UK, BI material,“n” = not from UK, BI material}
#'   \item{\code{data_source}}{character Data source that contributed the genome size measurement in question. “Šmarda et al., 2019”, “Zonneveld, 2019”, “C-ValueDB”, “Kew”} 
#'   \item{\code{sporophytic_chromosome_number}}{character Sporophytic chromosome number, determined from material from the Britain and Ireland. Summary report of available information per species. Numbers are uniformly quoted as sporophytic number irrespective of the tissue from which the count was derived. In doing this, particular care was taken in interpreting counts made on the gametophytes of apogamous ferns. Counts that are approximate in some way or have additional data, e.g. supernumerary chromosomes (suffix 's') or fragments (suffix 'f'), are listed here in addition to simple numbers. Approximate counts are cited with the prefix 'c.' or given as a range (sometimes with an indication of the mode). In a few cases reports from flow cytometry studies have been included and these are indicated using the format '4x(2n=68)' for example. Where different counts have been obtained from different cells from the same individual plant , the alternatives are separated by |, often with an indication that the plant is mixoploid where this is certain; occasionally it is unclear from the original work whether different chromosome numbers were recorded from different plants or from different cells within a plant.} 
#'   \item{\code{infraspecific_variation_chrom_number}}{character Where chromosome numbers are available, this column will indicate if diversity in chromosome counts has been observed in our dataset. For species with "y" the full range of counts is available in chrom_num_BI.csv. Information on infra-specific variation is coded as: "n" = no variation recorded, "m" = mixoploid variation, "p" = possible variation (owing to approximate counts), "s" = variation only in the presence and number of supernumerary chromosomes or fragments, "v" = variation present (euploid or aneuploid). In most cases, the "p" category is almost certainly "n" in reality.} 
#'}
#' @source \url{https://doi.org/10.5285/9f097d82-7560-4ed2-af13-604a9110cf6d}
"BI_main"